---
title: 第十章 异常处理
date: 2018-10-06 16:07:40
categories:
- Java学习
tags:
- Java
---

## 第十章 异常处理

### 一、使用try...catch捕获异常 

- 执行try块里的业务逻辑代码时出现异常，系统自动生成一个异常对象，该异常对象被提交给Java运行时环境，这个过程被称为抛出（throw）异常。
- Java运行时环境收到异常对象时，会寻找能处理该异常对象的catch块，如果找到合适的catch块并把该异常对象交给该catch块处理。
<!-- more -->
### 二、异常处理

```
try
{
	需要检测的代码；
}
catch(异常类  变量)
{
	异常处理代码；
}
finally
{
	一定会执行的代码；	
}
Finally代码块只有一种情况不会被执行。就是在之前执行了System.exit(0)。
```
- 资源回收
```
程序在try块里打开了一些物理资源（例如数据库连接、网络连接和磁盘文件等），这些物理资源都必须显式回收。 

为了保证一定能回收try块中打开的物理资源，异常处理机制提供了finally块。不管try块中的代码是否出现异常，也不管哪一个catch块被执行，finally块总会被执。 
```
